---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: true
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
  pre_tasks:
    - name: "Install rsync to be able to recieve the zipped artifacts from the CI server"
      become: true 
      become_method: sudo
      apt:
        name: rsync
        state: latest
    - name: "Install tar to be able to extract zipped artifacts"
      become: true 
      become_method: sudo
      apt:
        name: tar
        state: latest
    - name: "Install gzip to be able to extract the zipped artifacts"
      become: true 
      become_method: sudo
      apt:
        name: gzip
        state: latest
  roles:
    - deploy
