- name: Upgrade all packages 
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "Install nodejs"
  apt:
    name: nodejs
    state: latest
    update_cache: yes

- name: "Install npm"
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: "Install pm2"
  shell: npm install pm2 -g