---
- name: Copy the tar file from the control machine to the EC2 instance
  synchronize:
    src: ~/project/artifact.tar.gz
    dest: /back/

- name: Extract the app
  shell: |
    cd /back/
    tar –xvzf documents.tar.gz –C /back/end/
- name: Start the app
  shell: |
    cd /back/end/
    npm install
    pm2 stop default
    pm2 start npm -- start