---
- name: Copy the tar file from the control machine to the EC2 instance
  become: true
  become_user: root
  synchronize:
    src: ~/project/artifact/
    dest: /back/

- name: Extract the app
  become: true
  become_user: root
  shell: |
    cd /back/
    mkdir end
    tar xvzf artifact.tar.gz -C /back/end/
    
- name: Start the app
  become: true
  become_user: root
  shell: |
    cd /back/end/
    npm install
    pm2 stop default
    pm2 start npm -- start